//const ROOT_URL = "http://localhost:4000/";
const ROOT_URL = "https://asit-wb-backend.onrender.com/";

export const ApiUrls = {
		INTERNATIONALIZATIONLOAD: `${ROOT_URL}api/internationalization/`,
		INTERNATIONALIZATIONSAVE: `${ROOT_URL}api/internationalization/save/`,
		COLUMNSFETCH: `${ROOT_URL}api/columns`,
		COLUMNLIST: `${ROOT_URL}api/columns/list`,
		COLUMNSSAVE: `${ROOT_URL}api/columns/save`,
		COLUMNSDETAILS: `${ROOT_URL}api/columns/details/`,
		COLUMNSCREATE: `${ROOT_URL}api/columns/create`,
		COLUMNSUPDATE: `${ROOT_URL}api/columns/update/`,
		COLUMNSSTATUSUPDATE: `${ROOT_URL}api/columns/status`,
		IMAGEUPLOAD: `${ROOT_URL}api/image-upload`,
		REGISTRATION: `${ROOT_URL}api/registration`,
		SIGNUP: `${ROOT_URL}api/signup`,
		DUPLICATEEMAIL: `${ROOT_URL}api/check-duplicate-email`,
		USERLIST: `${ROOT_URL}api/users`,
		USERSCREATE: `${ROOT_URL}api/users/create`,
		USERSUPDATE: `${ROOT_URL}api/users/update/`,
		USERSTATUSUPDATE: `${ROOT_URL}api/users/status`,
		USERDELETE: `${ROOT_URL}api/users/delete`,
		USERDETAILS: `${ROOT_URL}api/users/details/`,
		USERPROFILEDETAILS: `${ROOT_URL}api/users/profile-details`,
		UPDATEPROFILE: `${ROOT_URL}api/update-profile`,
		UPDATEPROFILEIMAGE: `${ROOT_URL}api/update-profile-image`,
		USERSDATA: `${ROOT_URL}api/users-data`,
		INTERNATIONALIZATIONLIST: `${ROOT_URL}api/internationalization`,
		INTERNATIONALIZATIONSTATUSUPDATE: `${ROOT_URL}api/internationalization/status`,
		INTERNATIONALIZATIONDELETE: `${ROOT_URL}api/internationalization/delete`,
		INTERNATIONALIZATIONDETAILS: `${ROOT_URL}api/internationalization/details/`,
		INTERNATIONALIZATIONUPDATE: `${ROOT_URL}api/internationalization/update/`,
		USERLOGIN: `${ROOT_URL}api/login`,
		ADMINLOGIN: `${ROOT_URL}api/admin/login`,
		FORGOTPASSWORD: `${ROOT_URL}api/forgot-password-email`,
		VERIFYOTP: `${ROOT_URL}api/verify-otp`,
		RESENDOTP: `${ROOT_URL}api/resend-otp`,
		RESETPASSWORD: `${ROOT_URL}api/reset-password`,

	}	
